version: '3.8'

services:
  db:
    image: mysql
    container_name: db_todo
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - "./todo/src/main/resources/database/create_db.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - default
  appserver:
    build: ./todo/
    container_name: appserver
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - default

networks:
  default:
    driver: bridge
