version: '3.8'

services:
  db:
    image: mysql
    container_name: db_todo
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123456'