FROM maven:latest as builder
COPY ./ ./build

WORKDIR "/src"
ENTRYPOINT ["mvn", "clean", "package", "-DskipTests"] 

FROM tomcat:9.0.70-jdk11-corretto as server 
COPY --from=builder /build/target/todo.war /usr/local/tomcat/webapps/todo.war
COPY --from=builder /build/src/main/resources/server-conf/server.xml /usr/local/tomcat/conf/server.xml
COPY --from=builder /build/src/main/resources/server-conf/context.xml /usr/local/tomcat/conf/context.xml
